# Generated by Django 5.1.1 on 2024-09-14 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='recipes_app.ingredient'),
        ),
        migrations.AlterModelTable(
            name='ingredientamount',
            table='ingredient_amount',
        ),
    ]
