# Generated by Django 5.1.1 on 2024-09-20 06:36

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0002_delete_amount_alter_ingredientamount_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'created_at__year']),
        ),
    ]
