# Generated by Django 5.1.1 on 2024-09-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0005_alter_saveduserdish_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
