# Generated by Django 5.1.1 on 2024-09-21 12:32

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0006_alter_dishrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['date_joined__second', 'username', 'date_joined__microsecond']),
        ),
    ]
