# Generated by Django 5.1.1 on 2024-09-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_user_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='createduserdish',
            unique_together=set(),
        ),
    ]
