# Generated by Django 5.1.1 on 2024-09-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0008_alter_createduserdish_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CreatedUserDish',
        ),
    ]
