# Generated by Django 5.1.1 on 2024-09-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0009_dish_created_by_delete_createduserdish'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientamount',
            unique_together={('ingredient', 'amount')},
        ),
    ]
