# Generated by Django 5.1.1 on 2024-09-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0010_alter_ingredientamount_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'category')},
        ),
    ]
