# Generated by Django 5.1.1 on 2024-09-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0011_alter_ingredient_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='dishtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name', 'category']},
        ),
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ['ingredient', 'amount']},
        ),
    ]
