# Generated by Django 5.1.1 on 2024-09-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes_app", "0012_alter_category_options_alter_dishtype_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dishrating",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="ingredient",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="ingredientamount",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="dishrating",
            constraint=models.UniqueConstraint(
                fields=("dish", "user"), name="unique-dish-user"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="unique-name-category"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientamount",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "amount"), name="unique-ingredient-amount"
            ),
        ),
    ]
